// Generated by CoffeeScript 1.3.3
(function() {
  var create_sortable, save_sortable;

  $(function() {
    var $URL;
    $URL = $_GET("URL");
    if ($URL) {
      return create_sortable($URL);
    }
  });

  create_sortable = function($URL) {
    $('#banners_sortable').sortable({
      scroll: true,
      helper: fixHelper,
      axis: 'y',
      update: function() {
        return save_sortable($URL);
      }
    });
    return $('#banners_sortable').sortable('enable');
  };

  save_sortable = function($URL) {
    var serial;
    serial = $('#banners_sortable').sortable('serialize');
    return $.ajax({
      url: $URL,
      type: 'POST',
      data: serial
    });
  };

}).call(this);
